openapi: 3.1.0
info:
  title: Smarbar Backoffice AP
  description: Smarbar Backoffice AP
  version: 1.0.0
paths:
  /categories:
    get:
      tags:
        - Categories
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type:
                  - array
                items:
                  $ref: "#/components/schemas/category"
    post:
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/category"
      responses:
        201:
          description: Success
          $ref: "#/components/responses/201"
  /categories/{categoryId}:
    parameters:
      - name: categoryId
        schema:
          type: string
        in: path
    put:
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/category"
      responses:
        200:
          description: Entity successfully updated
    delete:
      tags:
        - Categories
      responses:
        200:
          description: Entity successfully deleted
    get:
      tags:
        - Categories
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
  /items:
    get:
      tags:
        - Items
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/item"
    post:
      tags:
        - Items
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/item"
      responses:
        201:
          $ref: "#/components/responses/201"
  /items/{itemId}:
    parameters:
      - name: itemId
        schema:
          type: string
        in: path
    put:
      tags:
        - Items
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/item"
      responses:
        200:
          description: Entity successfully updated
    delete:
      tags:
        - Items
      responses:
        200:
          description: Entity successfully deleted
    get:
      tags:
        - Items
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/item"
  /tables:
    get:
      tags:
        - Tables
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/table"
    post:
      tags:
        - Tables
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/table"
      responses:
        201:
          $ref: "#/components/responses/201"
  /tables/{tableId}:
    parameters:
      - name: tableId
        schema:
          type: string
        in: path
    put:
      tags:
        - Tables
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/table"
      responses:
        200:
          description: Entity successfully updated
    delete:
      tags:
        - Tables
      responses:
        200:
          description: Entity successfully deleted
    get:
      tags:
        - Tables
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/table"
components:
  schemas:
    category:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    item:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
        description:
          type: string
        picture:
          type: string
    table:
      type: object
      properties:
        name:
          type: string,
        seatCount:
          type: string,
        active:
          type: boolean
  responses:
    201:
      description: Entity successfully created
      headers:
        Location:
          description: Entity successfully created